"""baseline (no models yet)

Revision ID: be408b09e448
Revises: 
Create Date: 2026-08-15 18:18:17.458743

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'be408b09e448'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
